#!/usr/bin/ruby

require 'optparse'
require 'percolate-mail'

opts = OptionParser.new do |o|
	o.on("-p PORT", "--port PORT", Integer, 
		"Accept connections on port PORT (defaults to 10025)") do |port|
		$port = port
	end

	o.on("-i IPADDR", "--ip IPADDRESS", String,
		"Bind to IP address IPADDR (defaults to 0.0.0.0)") do |ip|
		$ip = ip
	end

	 o.on_tail("-h", "--help", "Show this message") do
		 puts opts
		 exit
	 end
end

opts.parse(ARGV)

listener = Percolate::Listener.new	:port => $port || 10025, :ipaddr => $ip || '0.0.0.0'
listener.go
